#!/usr/bin/env python3
import json
import os
import subprocess
import sys

# Read the source file
input_file = r"GenuisNet.ai\pages\reviews\cybersecurity\exabeam-batch2.json"

with open(input_file, 'r', encoding='utf-8') as f:
    data = json.load(f)

en_content = data['en']

# Prepare translations for each language
translations = {
    'pt': {
        'overview': 'Visão geral',
        'exabeam_is': 'O Exabeam é uma plataforma SIEM (Security Information and Event Management) de próxima geração que revoluciona operações de segurança por meio de análise comportamental e automação alimentada por IA. Ao contrário dos SIEMs tradicionais que sobrecarregam as equipes com alertas, o Exabeam usa aprendizado de máquina para compreender o comportamento normal do usuário e identifica automaticamente ameaças genuínas.',
        'smart_timelines': 'O recurso Smart Timelines da plataforma une automaticamente atividades do usuário de milhares de fontes de log em narrativas de ataque abrangentes, reduzindo drasticamente o tempo de investigação de horas para minutos. Os modelos comportamentais do Exabeam aprendem continuamente o que é normal para cada usuário, entidade e ativo, detectando anomalias que indicam contas comprometidas, ameaças internas e ataques sofisticados.',
        'cloud_native': 'Com arquitetura nativa de nuvem e ingestão de dados ilimitada nos níveis superiores, o Exabeam elimina as restrições de volume de dados que afligem os SIEMs legados, permitindo que as organizações coletem telemetria de segurança sem se preocupar com custos de licenciamento.',
        'key_features': 'Recursos principais',
        'auto_generated': 'Narrativas de ataque geradas automaticamente que correlacionam atividades do usuário em todas as fontes de dados em cronogramas visuais.',
        'ueba': 'Análise de Comportamento do Usuário e Entidade com modelos de ML que estabelecem linhas de base de comportamento normal e detectam anomalias.',
        'modern_architecture': 'Arquitetura moderna com ingestão de dados ilimitada, eliminando restrições de preços baseadas em volume.',
        'ai_driven': 'Triagem e automação de investigação orientadas por IA que priorizam ameaças reais e reduzem falsos positivos.',
        'pre_built': 'Casos de uso pré-construídos que cobrem a estrutura MITRE ATT&CK com atualizações contínuas de detecção.',
        'monitors_cloud': 'Monitora infraestrutura na nuvem, aplicativos SaaS, sistemas locais de uma única plataforma unificada.',
        'pros_cons': 'Prós e Contras',
        'advantages': 'Vantagens',
        'unlimited_data': 'Ingestão de dados ilimitada (níveis superiores)',
        'smart_timelines_reduce': 'Smart Timelines reduzem o tempo de investigação',
        'excellent_ueba': 'Excelentes capacidades de UEBA',
        'cloud_native_scalability': 'Escalabilidade nativa de nuvem',
        'lower_false': 'Taxa mais baixa de falsos positivos',
        'intuitive': 'Interface de investigação intuitiva',
        'strong_insider': 'Detecção forte de ameaças internas',
        'disadvantages': 'Desvantagens',
        'premium_pricing': 'Preços premium para recursos completos',
        'initial_behavior': 'Período inicial de linha de base comportamental',
        'less_mature': 'Menos maduro que Splunk/QRadar',
        'requires_soc': 'Requer conhecimento de analista de SOC',
        'custom_integrations': 'Integrações personalizadas podem ser complexas',
        'pricing': 'Preços',
        'tiered_licensing': 'O Exabeam usa licenciamento em camadas baseado em volume de dados e usuários:',
        'basic_siem': 'Capacidades básicas de SIEM. Preços baseados em volume de dados',
        'ueba_smart': 'UEBA e Smart Timelines. ~$15-25/usuário/mês',
        'unlimited_ingestion': 'Ingestão de dados ilimitada. Preços corporativos personalizados',
        'full_xdr': 'XDR completo com detecção na nuvem. Nível premium',
        'implementation': 'Implementação e ajuste disponíveis',
        'proof_of_value': 'Ensaios de prova de valor disponíveis',
        'best_use_cases': 'Melhores casos de uso',
        'excels_for': 'Exabeam se destaca para:',
        'enterprise_soc': 'Empresas SOC: Grandes equipes de operações de segurança que gerenciam altos volumes de dados',
        'insider_threat': 'Programas de Ameaça Interna: Organizações que priorizam detecção de ameaças internas',
        'cloud_first': 'Empresas Cloud-First: Negócios com infraestrutura SaaS e na nuvem extensiva',
        'compliance': 'Conformidade: Indústrias que exigem trilhos de auditoria abrangentes (finanças, saúde)',
        'legacy_siem': 'Substituição de SIEM Legado: Empresas migrando do Splunk/QRadar para plataforma moderna',
        'behavioral_analytics': 'Análise Comportamental: Equipes que desejam UEBA sem produtos separados',
        'may_not_be': 'Pode não ser ideal para:',
        'small_businesses': 'Pequenas empresas com menos de 500 funcionários (complexidade de preços)',
        'organizations_basic': 'Organizações com necessidades de segurança muito básicas',
        'companies_requiring': 'Empresas que exigem implantação extensiva no local',
        'teams_lacking': 'Equipes sem analistas de SOC experientes',
        'comparison': 'Comparação',
        'competitors': 'Exabeam vs Competidores',
        'vs_splunk': 'vs Splunk',
        'unlimited_option': 'Opção de ingestão de dados ilimitada',
        'better_ueba': 'Melhor UEBA pronta para uso',
        'smart_timelines_auto': 'Automação de Smart Timelines',
        'more_affordable': 'Mais acessível em escala',
        'vs_sentinel': 'vs Microsoft Sentinel',
        'superior_behavioral': 'Análise comportamental superior',
        'better_investigation': 'Fluxos de trabalho de investigação melhores',
        'multi_cloud': 'Suporte multi-nuvem',
        'less_azure': 'Menos centrado no Azure',
        'screenshots': 'Capturas de tela e interface',
        'explore': 'Explore a interface do Exabeam:',
        'faqs': 'Perguntas frequentes',
        'smart_timelines_q': 'Smart Timelines unem automaticamente todas as atividades de um usuário, ativo ou entidade de milhares de fontes de log em narrativas visuais cronológicas. Isso transforma a investigação de pesquisa em logs para revisão de histórias de ataque completas, reduzindo MTTI de horas para minutos.',
        'builds_behavioral': 'O Exabeam constrói linhas de base comportamentais para cada usuário e entidade usando aprendizado de máquina. Ele aprende o que é normal - horários de login típicos, locais, aplicativos acessados, volumes de dados - e atribui pontuações de risco a atividades anômalas. Múltiplas anomalias disparam alertas de alta prioridade indicando possível comprometimento.',
        'yes_fusion': 'Sim, com os níveis Fusion e Fusion XDR. Isso elimina o modelo de preço de volume de dados dos SIEMs tradicionais, permitindo ingerir logs de todas as fontes sem se preocupar com custos de licenciamento dimensionados por volume de dados.',
        'yes_migrate': 'Sim. Muitas organizações migram do Splunk e IBM QRadar para o Exabeam para arquitetura moderna de nuvem, ingestão de dados ilimitada e UEBA superior. Serviços de migração e suporte de implantação dupla disponíveis durante a transição.',
        'initial_behavioral_models': 'Os modelos comportamentais iniciais começam a fornecer valor dentro de 2-4 semanas. A precisão da linha de base completa melhora em 90 dias conforme o sistema aprende padrões. As regras de detecção de ameaças pré-construídas funcionam imediatamente enquanto a análise comportamental matura.',
        'final_verdict': 'Veredicto final',
        'excellent': 'Excelente',
        'exabeam_represents': 'O Exabeam representa o futuro do SIEM com sua análise comportamental, ingestão de dados ilimitada e automação de Smart Timelines. A plataforma reduz drasticamente o tempo de investigação e falsos positivos enquanto detecta ameaças sofisticadas que evitam sistemas baseados em regras. Ideal para empresas buscando SIEM moderno e nativo de nuvem que escala sem restrições de licenciamento tradicional.',
        'ueba_label': 'UEBA',
        'smart_timelines_label': 'Smart Timelines',
        'ease_of_use': 'Facilidade de uso',
        'value': 'Valor',
        'request_demo': 'Solicitar demonstração →',
        'compare_alternatives': 'Comparar alternativas'
    },
    'zh': {
        'overview': '概述',
        'exabeam_is': 'Exabeam是一个下一代SIEM（安全信息和事件管理）平台，通过行为分析和人工智能驱动的自动化革新了安全运营。与让团队应接不暇的传统SIEM不同，Exabeam使用机器学习来理解正常的用户行为，并自动识别真正的威胁。',
        'smart_timelines': '该平台的Smart Timelines功能自动将来自数千个日志源的用户活动整合成综合攻击叙述，将调查时间从数小时大幅缩短到几分钟。Exabeam的行为模型不断学习每个用户、实体和资产的正常行为，检测表明账户被入侵、内部威胁和复杂攻击的异常。',
        'cloud_native': '通过云原生架构和更高层级的无限数据摄入，Exabeam消除了困扰传统SIEM的数据量限制，使组织能够收集安全遥测数据，而无需担心许可成本。',
        'key_features': '关键功能',
        'auto_generated': '自动生成的攻击叙述，将来自所有数据源的用户活动关联到可视化时间线中。',
        'ueba': '用户和实体行为分析，具有建立正常行为基线并检测异常的ML模型。',
        'modern_architecture': '现代架构，无限数据摄入，消除基于数量的定价限制。',
        'ai_driven': '人工智能驱动的分类和调查自动化，优先处理真实威胁并减少误报。',
        'pre_built': '涵盖MITRE ATT&CK框架的预构建用例，具有持续的检测更新。',
        'monitors_cloud': '从单个统一平台监控云基础设施、SaaS应用、本地系统。',
        'pros_cons': '优点和缺点',
        'advantages': '优势',
        'unlimited_data': '无限数据摄入（更高层级）',
        'smart_timelines_reduce': 'Smart Timelines缩短调查时间',
        'excellent_ueba': '出色的UEBA能力',
        'cloud_native_scalability': '云原生可扩展性',
        'lower_false': '较低的误报率',
        'intuitive': '直观的调查界面',
        'strong_insider': '强大的内部威胁检测',
        'disadvantages': '劣势',
        'premium_pricing': '完整功能的高级定价',
        'initial_behavior': '初始行为基线周期',
        'less_mature': '不如Splunk/QRadar成熟',
        'requires_soc': '需要SOC分析员的专业知识',
        'custom_integrations': '自定义集成可能很复杂',
        'pricing': '定价',
        'tiered_licensing': 'Exabeam使用基于数据量和用户数的分层许可：',
        'basic_siem': '基本SIEM功能。基于数据量的定价',
        'ueba_smart': 'UEBA和Smart Timelines。~$15-25/用户/月',
        'unlimited_ingestion': '无限数据摄入。自定义企业定价',
        'full_xdr': '完整XDR与云检测。高级层',
        'implementation': '提供实施和调整',
        'proof_of_value': '提供价值证明试用',
        'best_use_cases': '最佳用例',
        'excels_for': 'Exabeam擅长：',
        'enterprise_soc': '企业SOC：管理高数据量的大型安全运营团队',
        'insider_threat': '内部威胁计划：优先检测内部威胁的组织',
        'cloud_first': '云优先公司：拥有广泛SaaS和云基础设施的企业',
        'compliance': '合规性：需要全面审计跟踪的行业（金融、医疗保健）',
        'legacy_siem': '传统SIEM替换：从Splunk/QRadar迁移到现代平台的公司',
        'behavioral_analytics': '行为分析：希望拥有UEBA但不需要单独产品的团队',
        'may_not_be': '可能不适合：',
        'small_businesses': '拥有少于500名员工的小企业（定价复杂性）',
        'organizations_basic': '只有非常基本安全需求的组织',
        'companies_requiring': '需要大量本地部署的公司',
        'teams_lacking': '缺乏经验丰富的SOC分析员的团队',
        'comparison': '比较',
        'competitors': 'Exabeam与竞争对手',
        'vs_splunk': '对比Splunk',
        'unlimited_option': '无限数据摄入选项',
        'better_ueba': '更好的开箱即用UEBA',
        'smart_timelines_auto': 'Smart Timelines自动化',
        'more_affordable': '大规模更经济',
        'vs_sentinel': '对比Microsoft Sentinel',
        'superior_behavioral': '优越的行为分析',
        'better_investigation': '更好的调查工作流',
        'multi_cloud': '多云支持',
        'less_azure': '不太以Azure为中心',
        'screenshots': '屏幕截图和界面',
        'explore': '探索Exabeam界面：',
        'faqs': '常见问题',
        'smart_timelines_q': 'Smart Timelines自动将用户、资产或实体的所有活动从数千个日志源整合成按时间顺序排列的可视叙述。这将调查从搜索日志转变为查看完整的攻击故事，将MTTI从数小时缩短到分钟。',
        'builds_behavioral': 'Exabeam使用机器学习为每个用户和实体构建行为基线。它学习什么是正常的——典型的登录时间、位置、访问的应用程序、数据量——并为异常活动分配风险分数。多个异常触发高优先级警报，表明可能的入侵。',
        'yes_fusion': '是的，使用Fusion和Fusion XDR层。这消除了传统SIEM的数据量定价模型，允许您从所有来源摄入日志，而无需担心许可成本随数据量扩展。',
        'yes_migrate': '是的。许多组织从Splunk和IBM QRadar迁移到Exabeam，以获得现代云架构、无限数据摄入和优越的UEBA。迁移过程中提供迁移服务和双部署支持。',
        'initial_behavioral_models': '初始行为模型在2-4周内开始提供价值。完整基线准确性在90天内改进，因为系统学习模式。预构建的威胁检测规则立即生效，而行为分析随时成熟。',
        'final_verdict': '最终判决',
        'excellent': '优秀',
        'exabeam_represents': 'Exabeam代表SIEM的未来，具有行为分析、无限数据摄入和Smart Timelines自动化。该平台大幅减少调查时间和误报，同时检测逃避基于规则的系统的复杂威胁。理想适用于寻求无需传统许可限制即可扩展的现代云原生SIEM的企业。',
        'ueba_label': '用户和实体行为分析',
        'smart_timelines_label': '智能时间线',
        'ease_of_use': '易用性',
        'value': '价值',
        'request_demo': '请求演示 →',
        'compare_alternatives': '比较替代方案'
    },
    'ja': {
        'overview': '概要',
        'exabeam_is': 'Exabeamは、行動分析とAIを活用した自動化により、セキュリティ運用に革新をもたらす次世代SIEM（セキュリティ情報とイベント管理）プラットフォームです。アラート過多でチームに負担をかける従来型SIEMとは異なり、Exabeamは機械学習を使用して通常のユーザー行動を理解し、真の脅威を自動的に検出します。',
        'smart_timelines': 'このプラットフォームのSmart Timelinesフィーチャーは、数千のログソースからのユーザーアクティビティを自動的に結合して、包括的な攻撃叙述を作成します。調査時間を数時間から数分へと劇的に短縮します。Exabeamの行動モデルは、各ユーザー、エンティティ、アセットの正常な動作を継続的に学習し、アカウント侵害、内部脅威、高度な攻撃を示す異常を検出します。',
        'cloud_native': 'クラウドネイティブアーキテクチャと上位階層における無制限のデータ取り込みにより、Exabeamは従来型SIEMを悩ませるデータ量の制限を排除し、ライセンス料金を心配することなくセキュリティテレメトリを収集できるようにします。',
        'key_features': '主な機能',
        'auto_generated': 'すべてのデータソースからのユーザーアクティビティを視覚的タイムラインに関連付ける自動生成された攻撃叙述。',
        'ueba': '通常の行動をベースライン化し、異常を検出するMLモデルを備えたユーザーおよびエンティティ行動分析。',
        'modern_architecture': 'ボリュームベースの価格設定制限を排除する、無制限のデータ取り込みを備えた最新アーキテクチャ。',
        'ai_driven': '実際の脅威を優先し、誤検知を削減するAI駆動のトリアージと調査自動化。',
        'pre_built': 'MITRE ATT&CKフレームワークをカバーする事前構築されたユースケース、継続的な検出アップデート。',
        'monitors_cloud': 'クラウドインフラストラクチャ、SaaSアプリ、オンプレミスシステムを単一統合プラットフォームから監視。',
        'pros_cons': 'メリット＆デメリット',
        'advantages': 'メリット',
        'unlimited_data': '無制限のデータ取り込み（上位階層）',
        'smart_timelines_reduce': 'Smart Timelinesで調査時間を短縮',
        'excellent_ueba': '優れたUEBA機能',
        'cloud_native_scalability': 'クラウドネイティブのスケーラビリティ',
        'lower_false': '低い誤検知率',
        'intuitive': '直感的な調査インターフェース',
        'strong_insider': '強力な内部脅威検出',
        'disadvantages': 'デメリット',
        'premium_pricing': '全機能の高価な価格設定',
        'initial_behavior': '初期行動ベースラインの期間',
        'less_mature': 'Splunk/QRadarより成熟度が低い',
        'requires_soc': 'SOCアナリストの専門知識が必要',
        'custom_integrations': 'カスタム統合は複雑な場合がある',
        'pricing': '価格',
        'tiered_licensing': 'Exabeamはデータ量とユーザー数に基づくティアード型ライセンスを使用：',
        'basic_siem': '基本的なSIEM機能。データ量ベースの価格設定',
        'ueba_smart': 'UEBAおよびSmart Timelines。約$15-25/ユーザー/月',
        'unlimited_ingestion': '無制限のデータ取り込み。カスタムエンタープライズ価格',
        'full_xdr': 'クラウド検出を備えた完全XDR。プレミアム階層',
        'implementation': '実装と調整が利用可能',
        'proof_of_value': '価値実証トライアルが利用可能',
        'best_use_cases': '最適なユースケース',
        'excels_for': 'Exabeamが優れている対象：',
        'enterprise_soc': 'エンタープライズSOC：高いデータ量を管理する大規模セキュリティ運用チーム',
        'insider_threat': 'インサイダー脅威プログラム：内部脅威検出を優先する組織',
        'cloud_first': 'クラウドファースト企業：広範なSaaSおよびクラウドインフラストラクチャを持つ企業',
        'compliance': 'コンプライアンス：包括的な監査証跡が必要な業界（金融、医療）',
        'legacy_siem': 'レガシーSIEM置換：SplunkおよびQRadarから最新プラットフォームへの移行企業',
        'behavioral_analytics': '行動分析：別の製品を使わずにUEBAが必要なチーム',
        'may_not_be': '適さない場合：',
        'small_businesses': '従業員500人未満の小規模企業（価格設定の複雑さ）',
        'organizations_basic': '非常に基本的なセキュリティニーズの組織',
        'companies_requiring': '広範なオンプレミスデプロイメントが必要な企業',
        'teams_lacking': '経験豊富なSOCアナリストのいないチーム',
        'comparison': '比較',
        'competitors': 'Exabeam対競合製品',
        'vs_splunk': '対Splunk',
        'unlimited_option': '無制限のデータ取り込みオプション',
        'better_ueba': 'より優れたUEBAの初期実装',
        'smart_timelines_auto': 'Smart Timelinesの自動化',
        'more_affordable': '大規模ではより手頃',
        'vs_sentinel': '対Microsoft Sentinel',
        'superior_behavioral': '優れた行動分析',
        'better_investigation': 'より優れた調査ワークフロー',
        'multi_cloud': 'マルチクラウドサポート',
        'less_azure': 'Azureへの依存度が低い',
        'screenshots': 'スクリーンショットとインターフェース',
        'explore': 'Exabeamのインターフェースを確認：',
        'faqs': 'よくある質問',
        'smart_timelines_q': 'Smart Timelinesは、数千のログソースからユーザー、アセット、またはエンティティのすべてのアクティビティを自動的に結合し、時系列の視覚的叙述にします。これにより、調査がログの検索から完全な攻撃物語のレビューへと変わり、MTTIが数時間から分に短縮されます。',
        'builds_behavioral': 'Exabeamは機械学習を使用して、すべてのユーザーとエンティティの行動ベースラインを構築します。通常の状態（典型的なログイン時間、場所、アクセスされたアプリケーション、データ量）を学習し、異常なアクティビティにリスクスコアを割り当てます。複数の異常が高優先度アラートをトリガーし、侵害の可能性を示します。',
        'yes_fusion': 'はい、FusionおよびFusion XDRティアー。これにより、従来のSIEMのデータ量ベースの価格設定モデルが廃止され、ライセンス料金が増加することを心配せずにすべてのソースからログを取り込めます。',
        'yes_migrate': 'はい。多くの組織がSplunkおよびIBM QRadarからExabeamに移行し、最新のクラウドアーキテクチャ、無制限のデータ取り込み、優れたUEBAを実現しています。移行中に移行サービスとデュアルデプロイメントサポートが利用可能です。',
        'initial_behavioral_models': '初期行動モデルは2～4週間以内に価値提供を開始します。完全なベースラインの精度は90日以上にわたって改善され、システムがパターンを学習します。事前構築された脅威検出ルールは即座に機能し、行動分析は徐々に成熟します。',
        'final_verdict': '最終判定',
        'excellent': '優秀',
        'exabeam_represents': 'Exabeamは、行動分析、無制限のデータ取り込み、Smart Timelinesの自動化により、SIEMの未来を表しています。このプラットフォームは調査時間と誤検知を劇的に削減すると同時に、ルールベースシステムを回避する高度な脅威を検出します。従来のライセンス制限なしでスケールできる最新のクラウドネイティブSIEMを求めるエンタープライズに理想的です。',
        'ueba_label': 'UEBA',
        'smart_timelines_label': 'スマートタイムライン',
        'ease_of_use': '使いやすさ',
        'value': '価値',
        'request_demo': 'デモをリクエスト →',
        'compare_alternatives': '代替案を比較'
    }
}

# Build complete translation objects
def map_english_to_translation(en_dict, lang_translations):
    """Map English keys to translated values"""
    result = {}

    # Manual mapping based on key structure
    key_mapping = {
        'review.exabeam.overview': 'overview',
        'review.exabeam.exabeam.is.a.next-generation.siem': 'exabeam_is',
        'review.exabeam.the.platforms.smart.timelines.feature': 'smart_timelines',
        'review.exabeam.with.cloud-native.architecture.and.unlimited': 'cloud_native',
        'review.exabeam.key.features': 'key_features',
        'review.exabeam.auto-generated.attack.narratives.that.correlate': 'auto_generated',
        'review.exabeam.user.and.entity.behavior.analytics': 'ueba',
        'review.exabeam.modern.architecture.with.unlimited.data': 'modern_architecture',
        'review.exabeam.ai-driven.triage.and.investigation.automation': 'ai_driven',
        'review.exabeam.pre-built.use.cases.covering.mitre': 'pre_built',
        'review.exabeam.monitors.cloud.infrastructure.saas.apps': 'monitors_cloud',
        'review.exabeam.pros.cons': 'pros_cons',
        'review.exabeam.advantages': 'advantages',
        'review.exabeam.unlimited.data.ingestion.higher.tiers': 'unlimited_data',
        'review.exabeam.smart.timelines.reduce.investigation.time': 'smart_timelines_reduce',
        'review.exabeam.excellent.ueba.capabilities': 'excellent_ueba',
        'review.exabeam.cloud-native.scalability': 'cloud_native_scalability',
        'review.exabeam.lower.false.positive.rate': 'lower_false',
        'review.exabeam.intuitive.investigation.interface': 'intuitive',
        'review.exabeam.strong.insider.threat.detection': 'strong_insider',
        'review.exabeam.disadvantages': 'disadvantages',
        'review.exabeam.premium.pricing.for.full.features': 'premium_pricing',
        'review.exabeam.initial.behavior.baseline.period': 'initial_behavior',
        'review.exabeam.less.mature.than.splunkqradar': 'less_mature',
        'review.exabeam.requires.soc.analyst.expertise': 'requires_soc',
        'review.exabeam.custom.integrations.can.be.complex': 'custom_integrations',
        'review.exabeam.pricing': 'pricing',
        'review.exabeam.exabeam.uses.tiered.licensing.based': 'tiered_licensing',
        'review.exabeam.basic.siem.capabilities.data.volume-based': 'basic_siem',
        'review.exabeam.ueba.and.smart.timelines.15-25usermonth': 'ueba_smart',
        'review.exabeam.unlimited.data.ingestion.custom.enterprise': 'unlimited_ingestion',
        'review.exabeam.full.xdr.with.cloud.detection': 'full_xdr',
        'review.exabeam.implementation.and.tuning.available': 'implementation',
        'review.exabeam.proof.of.value.trials.available': 'proof_of_value',
        'review.exabeam.best.use.cases': 'best_use_cases',
        'review.exabeam.exabeam.excels.for': 'excels_for',
        'review.exabeam.enterprise.soc.large.security.operations': 'enterprise_soc',
        'review.exabeam.insider.threat.programs.organizations.prioritizing': 'insider_threat',
        'review.exabeam.cloud-first.companies.businesses.with.extensive': 'cloud_first',
        'review.exabeam.compliance.industries.requiring.comprehensive.audit': 'compliance',
        'review.exabeam.legacy.siem.replacement.companies.migrating': 'legacy_siem',
        'review.exabeam.behavioral.analytics.teams.wanting.ueba': 'behavioral_analytics',
        'review.exabeam.may.not.be.ideal.for': 'may_not_be',
        'review.exabeam.small.businesses.under.500.employees': 'small_businesses',
        'review.exabeam.organizations.with.very.basic.security': 'organizations_basic',
        'review.exabeam.companies.requiring.extensive.on-premise.deployment': 'companies_requiring',
        'review.exabeam.teams.lacking.experienced.soc.analysts': 'teams_lacking',
        'review.exabeam.comparison': 'comparison',
        'review.exabeam.exabeam.vs.competitors': 'competitors',
        'review.exabeam.vs.splunk': 'vs_splunk',
        'review.exabeam.unlimited.data.ingestion.option': 'unlimited_option',
        'review.exabeam.better.ueba.out-of-box': 'better_ueba',
        'review.exabeam.smart.timelines.automation': 'smart_timelines_auto',
        'review.exabeam.more.affordable.at.scale': 'more_affordable',
        'review.exabeam.vs.microsoft.sentinel': 'vs_sentinel',
        'review.exabeam.superior.behavioral.analytics': 'superior_behavioral',
        'review.exabeam.better.investigation.workflows': 'better_investigation',
        'review.exabeam.multi-cloud.support': 'multi_cloud',
        'review.exabeam.less.azure-centric': 'less_azure',
        'review.common.screenshots.interface': 'screenshots',
        'review.exabeam.explore.exabeams.interface': 'explore',
        'review.exabeam.frequently.asked.questions': 'faqs',
        'review.exabeam.smart.timelines.automatically.stitch.together': 'smart_timelines_q',
        'review.exabeam.exabeam.builds.behavioral.baselines.for': 'builds_behavioral',
        'review.exabeam.yes.with.fusion.and.fusion': 'yes_fusion',
        'review.exabeam.yes.many.organizations.migrate.from': 'yes_migrate',
        'review.exabeam.initial.behavioral.models.start.providing': 'initial_behavioral_models',
        'review.exabeam.final.verdict': 'final_verdict',
        'review.exabeam.excellent': 'excellent',
        'review.exabeam.exabeam.represents.the.future.of': 'exabeam_represents',
        'review.exabeam.ueba': 'ueba_label',
        'review.exabeam.smart.timelines': 'smart_timelines_label',
        'review.exabeam.ease.of.use': 'ease_of_use',
        'review.exabeam.value': 'value',
        'review.exabeam.request.demo': 'request_demo',
        'review.exabeam.compare.alternatives': 'compare_alternatives'
    }

    for en_key in en_dict:
        if en_key in key_mapping:
            translation_key = key_mapping[en_key]
            if translation_key in lang_translations:
                result[en_key] = lang_translations[translation_key]
            else:
                result[en_key] = en_dict[en_key]  # Fallback to English
        else:
            result[en_key] = en_dict[en_key]  # Fallback to English

    return result

# Generate translations for each language
output_data = {'en': en_content}

for lang in ['pt', 'zh', 'ja']:
    output_data[lang] = map_english_to_translation(en_content, translations[lang])

# Write to file
output_file = input_file
with open(output_file, 'w', encoding='utf-8') as f:
    json.dump(output_data, f, ensure_ascii=False, indent=2)

print(f"Successfully translated exabeam-batch2.json to pt, zh, ja")
print(f"File saved to: {output_file}")
